# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 22, 20, 27, 31, 752963, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
